version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"
