version: 2.1

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - store_artifacts:
          path: index.html
          destination: index.html
                                     
workflows:
  wkfw:
    jobs:
      - premier
