version: 2.1

parameters:
  IGNORE_UNIT_TEST:
    type: boolean
    default: false
    
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo << pipeline.parameters.IGNORE_UNIT_TEST >>
