version: 2.1

parameters:
  deploy_prod:
    type: boolean
    default: false
    
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo << pipeline.parameters.deploy_prod >>
